# This file arranges for the build server for tests and automatic
# deployment to PyPI such that we can pip install.

notifications:
  email: false

language: python

# Deploy releases to PyPI for pip installs
# See https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    - TWINE_USERNAME=NESTCollaboration
    - secure: "IgoVu7BeBx2mfNdq3mUbVyiUKF7DcNNx90lEFu5Du9CSOsO19q/wxIXD4mVNFXDO4uXEUIy/7386hJlDXrKrGeQ4W6jiAuPdQJ2KAhcZ1Jnkg0OQoXDtt8Y3WrldWahH+XNS7msIFGuWflbaTSRsOdnBLgulV8Uzp7cb6YIYyY88a+pZtqMKrhYWP/MyWUvm+JqCcs0lIYO95J0tSmAgpN9iLlThoyNKKLYf2IVRCjfWt4uQFJBrUyw3PleokDSHIEYAz7AFWA+71pjhRrzWFkN0Ot1BaPDCQWRiWlG+hR191lI7Ui8rOmaU5zuvx6Na57vMlG7XLOBOq0vgt1hNy0GqKoyxA4ZPqoMdc2Qqo/bh8G/goNfOsGwm00WfyQRvQiGmsGh/KLOGLfbvD9PzmKf44UEHOEAuBVHUMCKLEI+1W9H3IQhmQ3dGJjYpTLT9R9m+wuDv/cwr64ValJUcWIcYCbtNUefHJD6bpoEzLtm5QFF4jxmE/SMVHActlfWUEbuiggaR55/TT8cuoJ7gf4ZNEu0XI7zhacwpQVSHmWVybG94JTrjQ+CfDxMY1QB0Ilg0QVgoEU8+D4rd0iUprxaWndiw35w7h8DLO82RRVG3xjePtG4G47g/5Z3BmB36NkEDsMBgV2+5IJlolnrImn/fELq5R73LoHl9gnQUpkw="
    
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
      - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
- docker pull $DOCKER_IMAGE

script:
    - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
    - ls wheelhouse/

after_success:
    - pip install twine
    - echo TRAVIS_TAG $TRAVIS_TAG
    - if [ "${TRAVIS_TAG}" == "true" ]; then python -m twine upload wheelhouse/*.whl; fi
